import AppKit

struct CapturedTextEvent {
    let text: String
    let sourceApp: String?
    let sourceAppName: String?
    let timestamp: Date
}

@MainActor
final class ClipboardWatcher {
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: (CapturedTextEvent) -> Void
    private(set) var isPaused: Bool = false

    init(onCapture: @escaping (CapturedTextEvent) -> Void) {
        self.lastChangeCount = NSPasteboard.general.changeCount
        self.onCapture = onCapture
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.tick()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func setPaused(_ paused: Bool) { isPaused = paused }

    private func tick() {
        guard !isPaused else { return }
        let pb = NSPasteboard.general
        let current = pb.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Skip-rules: privacy markers from nspasteboard.org and 1Password.
        if let types = pb.types {
            for skip in Self.skippedTypes where types.contains(NSPasteboard.PasteboardType(skip)) {
                _ = skip
                return
            }
        }

        // M1 captures text only. File capture lands in the next chunk.
        guard let text = pb.string(forType: .string), !text.isEmpty else { return }

        let app = NSWorkspace.shared.frontmostApplication
        if let bundleId = app?.bundleIdentifier, Self.skippedSourceApps.contains(bundleId) {
            return
        }

        onCapture(
            CapturedTextEvent(
                text: text,
                sourceApp: app?.bundleIdentifier,
                sourceAppName: app?.localizedName,
                timestamp: Date()
            )
        )
    }

    private static let skippedTypes: [String] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "Hide"
    ]

    private static let skippedSourceApps: Set<String> = [
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.5",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.lastpass.LastPassMacApp",
        "org.keepassxc.keepassxc"
    ]
}
