import AppKit
import SwiftUI

final class OverlayPanelController {
    private let panel: NSPanel
    private var hostingView: NSHostingView<OverlayView>!
    private let store: HistoryStore

    var isVisible: Bool { panel.isVisible }

    init(store: HistoryStore) {
        self.store = store

        let size = NSSize(width: 720, height: 480)
        panel = NSPanel(
            contentRect: NSRect(origin: .zero, size: size),
            styleMask: [.titled, .fullSizeContentView, .nonactivatingPanel, .resizable],
            backing: .buffered,
            defer: false
        )
        panel.titleVisibility = .hidden
        panel.titlebarAppearsTransparent = true
        panel.isMovableByWindowBackground = true
        panel.standardWindowButton(.closeButton)?.isHidden = true
        panel.standardWindowButton(.miniaturizeButton)?.isHidden = true
        panel.standardWindowButton(.zoomButton)?.isHidden = true
        panel.backgroundColor = .clear
        panel.hasShadow = true
        panel.level = .floating
        panel.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary, .stationary]
        panel.isReleasedWhenClosed = false
        panel.becomesKeyOnlyIfNeeded = false
        panel.hidesOnDeactivate = false

        let host = NSHostingView(rootView: OverlayView(
            store: store,
            onPaste: { _ in },
            onDismiss: {}
        ))
        host.translatesAutoresizingMaskIntoConstraints = false
        self.hostingView = host

        let container = NSView()
        container.addSubview(host)
        NSLayoutConstraint.activate([
            host.topAnchor.constraint(equalTo: container.topAnchor),
            host.bottomAnchor.constraint(equalTo: container.bottomAnchor),
            host.leadingAnchor.constraint(equalTo: container.leadingAnchor),
            host.trailingAnchor.constraint(equalTo: container.trailingAnchor),
        ])
        panel.contentView = container

        host.rootView = OverlayView(
            store: store,
            onPaste: { [weak self] entry in self?.paste(entry) },
            onDismiss: { [weak self] in self?.hide() }
        )
    }

    func toggle() { panel.isVisible ? hide() : show() }

    func show() {
        panel.center()
        panel.makeKeyAndOrderFront(nil)
    }

    func hide() {
        panel.orderOut(nil)
    }

    private func paste(_ entry: ClipEntry) {
        do {
            let payloads = try store.payloads(for: entry.id)
            switch entry.kind {
            case .text, .url, .richText:
                if let text = payloads.first?.inlineText {
                    pasteText(text)
                }
            case .file, .multiFile:
                pasteFiles(payloads)
            case .image:
                break
            }
        } catch {
            print("[Paste] failed: \(error)")
        }
        hide()
    }

    private func pasteText(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        // Mark as auto-generated so our own watcher skips this self-write.
        pb.setData(Data(), forType: Self.autoGeneratedType)
        print("[Paste] text written; pb.changeCount=\(pb.changeCount)")
    }

    private func pasteFiles(_ payloads: [ClipPayload]) {
        var resolved: [URL] = []
        for payload in payloads {
            guard let bookmark = payload.bookmarkData else {
                print("[Paste] payload has no bookmark: \(payload.filename ?? "?")")
                continue
            }
            var stale = false
            do {
                let url = try URL(
                    resolvingBookmarkData: bookmark,
                    options: [.withSecurityScope],
                    relativeTo: nil,
                    bookmarkDataIsStale: &stale
                )
                let started = url.startAccessingSecurityScopedResource()
                print("[Paste] resolved \(url.path) stale=\(stale) accessStarted=\(started)")
                resolved.append(url)
            } catch {
                print("[Paste] bookmark resolve failed for \(payload.filename ?? "?"): \(error)")
            }
        }
        guard !resolved.isEmpty else {
            print("[Paste] no URLs resolved")
            return
        }

        let pb = NSPasteboard.general
        pb.clearContents()

        // Canonical: writeObjects with NSURLs gives Finder/apps the standard
        // public.file-url per item with the right format.
        let success = pb.writeObjects(resolved as [NSURL])

        // Legacy NSFilenamesPboardType — many older apps & Finder paste handlers still expect this.
        pb.setPropertyList(
            resolved.map(\.path),
            forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")
        )

        // Auto-generated marker → our watcher skips this self-write so we don't dup.
        pb.setData(Data(), forType: Self.autoGeneratedType)

        print("[Paste] wrote \(resolved.count) file URL(s); writeObjects=\(success); pb.changeCount=\(pb.changeCount); types=\(pb.types?.map(\.rawValue) ?? [])")

        // Hold security scope ~30s so the destination can finish reading.
        let urls = resolved
        Task {
            try? await Task.sleep(nanoseconds: 30_000_000_000)
            for url in urls {
                url.stopAccessingSecurityScopedResource()
            }
        }
    }

    private static let autoGeneratedType =
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}
