/* global React, Icon, useDownloadUrl */

function PrivacySection() {
  const points = [
    {
      icon: <Icon.database/>,
      tone: "blue",
      title: "Stays on your Mac",
      body: <>Your history lives in the app's macOS sandbox container. No account. No uploads. No telemetry. The only thing the app ever connects to is its own update check.</>,
    },
    {
      icon: <Icon.lock/>,
      tone: "purple",
      title: "Skips supported password managers",
      body: <>Copies made while 1Password, Bitwarden, Dashlane, KeePassXC, Apple Passwords, Keychain Access, or LastPass is frontmost are ignored. Add any app to the skip list in Settings.</>,
    },
    {
      icon: <Icon.shield/>,
      tone: "amber",
      title: "Honors confidential copies",
      body: <>A clipboard item marked concealed, transient, or automatically generated by its source app is not recorded, even when that app is not on the built-in skip list.</>,
    },
    {
      icon: <Icon.pause/>,
      tone: "green",
      title: "Pause with one click",
      body: <>Hit Pause Recording in the menu bar and nothing is captured until you resume — even across restarts. The overlay shows a Paused badge so you always know.</>,
    },
  ];

  const skipped = [
    { name: "1Password",       color: "#0572ec", letter: "1" },
    { name: "Bitwarden",       color: "#175ddc", letter: "B" },
    { name: "Dashlane",        color: "#007c89", letter: "D" },
    { name: "KeePassXC",       color: "#3c4d5c", letter: "K" },
    { name: "Apple Passwords", color: "#9aa0a6", letter: "P" },
    { name: "Keychain Access", color: "#3a3a3c", letter: "K" },
    { name: "LastPass",        color: "#d32d27", letter: "L" },
  ];

  return (
    <section className="privacy" aria-labelledby="privacy-heading">
      <div className="container">
        <div className="section-eyebrow">Privacy</div>
        <h2 id="privacy-heading" className="section-title">Your clipboard, yours alone.</h2>
        <p className="section-lede">
          Your clipboard has private things in it — an address, a card number, that message you almost sent. The app treats it that way.
        </p>
        <p className="section-more"><a href="/privacy/">Read the complete privacy overview <span aria-hidden="true">→</span></a></p>

        <div className="privacy-grid">
          <ul className="privacy-points" aria-label="Privacy guarantees">
            {points.map((p, i) => (
              <li key={i} className="privacy-point" data-tone={p.tone}>
                <div className="pp-icon" aria-hidden="true">{p.icon}</div>
                <div>
                  <h3>{p.title}</h3>
                  <p>{p.body}</p>
                </div>
              </li>
            ))}
          </ul>
          <div className="privacy-aside">
            <div className="skip-card" role="group" aria-labelledby="skip-card-title">
              <div className="skip-card-head" id="skip-card-title">
                <span aria-hidden="true"><Icon.shield/></span> Password managers it ignores from day one
              </div>
              <ul className="skip-grid" aria-label="Ignored password managers">
                {skipped.map((a, i) => (
                  <li key={i} className="skip-chip">
                    <div className="app-icon" style={{background: a.color}} aria-hidden="true">{a.letter}</div>
                    <span>{a.name}</span>
                  </li>
                ))}
                <li className="skip-chip skip-chip-add" aria-label="Add more apps in Settings">
                  <div className="app-icon app-icon-add" aria-hidden="true">+</div>
                  <span>Add more in Settings</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function CheatsheetSection() {
  const steps = [
    { n: "01", title: "Copy normally", body: "Keep using Command + C in any Mac app. Clipboard History quietly remembers each copy." },
    { n: "02", title: "Press Shift + Command + V", body: "The history panel opens over the app you're using, with search ready immediately." },
    { n: "03", title: "Find it and press Return", body: "Type a word and choose with the arrow keys. Optional auto-paste returns it to your app; otherwise press Command + V." },
  ];

  return (
    <section aria-labelledby="shortcuts-heading">
      <div className="container">
        <div className="section-eyebrow">How it works</div>
        <h2 id="shortcuts-heading" className="section-title">Copy. Find. Paste.</h2>
        <p className="section-lede">
          Three simple steps, entirely from the keyboard. The default shortcut is customizable whenever you want it to be.
        </p>
        <div className="workflow-grid">
          {steps.map((step) => (
            <article className="workflow-step" key={step.n}>
              <span className="workflow-number" aria-hidden="true">{step.n}</span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
            </article>
          ))}
        </div>
        <p className="section-more section-more-center"><a href="/keyboard-shortcuts/">See every keyboard shortcut <span aria-hidden="true">→</span></a></p>
      </div>
    </section>
  );
}

function FAQSection() {
  const faqs = [
    { q: "Is Clipboard History free?", a: "Yes. Free, open source, no account, no trial, no ads. The code is on GitHub if you want to look at it." },
    { q: "Will it record my passwords?", a: "Copies made while a supported password manager is frontmost are skipped, as are clipboard items their source app marks concealed, transient, or automatically generated. Clipboard History cannot identify every secret copied as ordinary content, so exclude other sensitive apps in Settings → Privacy or pause recording when needed." },
    { q: "Which Macs does it work on?", a: "Any Mac running macOS 14 (Sonoma) or newer. Apple Silicon and Intel both supported." },
    { q: "Will it slow down my Mac?", a: "It is designed to stay out of the way, checking the clipboard twice a second. Finder items are stored by reference, and text, rich-text, and image payloads are limited by the size cap in Settings. Download size varies by release." },
    { q: "How is this different from the built-in macOS clipboard?", a: "macOS 26 Tahoe includes recent clipboard history in Spotlight: press Command + Space, then Command + 4. Clipboard History also supports macOS 14 Sonoma and macOS 15 Sequoia, keeps 1,000 items by default (adjustable up to 10,000), opens directly with Shift + Command + V, saves Finder file and folder references, and keeps starred or grouped clips until you remove them." },
    { q: "How does it compare to Paste, Maccy, or Alfred's clipboard?", a: "Clipboard History is free, open source, and focused. Paste is paid and syncs across devices. Maccy is also free and open source, while Alfred's clipboard comes with the Powerpack. Clipboard History keeps history local and handles Finder references in detail; choose another tool if you need cloud sync, OCR, QR recognition, editing, or automation." },
    { q: "Does it sync between my Macs?", a: "No, and it won't. Your clipboard often contains passwords, private messages, and tokens — sending that to a server (even Apple's) is a tradeoff we don't want to make on your behalf. Clipboard History stays on the Mac it's installed on." },
    { q: "Where is my clipboard data stored?", a: "In a SQLite file inside the app's macOS sandbox container at ~/Library/Containers/app.clipboard-history/Data/Library/Application Support/Clipboard History/clipboard.sqlite. Nothing is uploaded. Updates migrate history from the older unsandboxed location." },
    { q: "What can it capture?", a: "It captures plain text and links, preserves RTF or HTML with a plain-text fallback, and stores direct PNG or TIFF clipboard images with bounded preview thumbnails. Finder files and folders are saved by reference, not duplicated. It does not perform OCR, QR recognition, or image-content search." },
    { q: "Can I change the shortcut? The theme?", a: "Both. Record any keyboard shortcut in Settings → General — Shift + Command + V is just the default. And the app follows your choice of System, Light, or Dark appearance: switch it in Settings or with the sun/moon button right inside the overlay." },
    { q: "Does it start automatically?", a: "You choose whether to launch at login during first-run setup, and can change that choice later in Settings → General. Clipboard recording starts only after setup is complete. The app then lives in the menu bar with no Dock icon." },
    { q: "Why does auto-paste request permission?", a: "Automatic paste needs macOS permission to post the Command + V keyboard event. The permission is optional: without it, pressing Return still puts the selected clip on the clipboard, and you paste manually with Command + V." },
    { q: "How do updates work?", a: "The download is signed and notarized by Apple, so you won't see the scary \"unidentified developer\" warning. The app checks for updates in the background and every update is cryptographically verified before it installs (it uses Sparkle, the standard open-source updater for Mac apps). You can also check manually from the menu bar." },
    { q: "How do I uninstall Clipboard History?", a: "Quit the app from the menu bar, then drag Clipboard History from Applications to the Trash. To erase history first, use Settings → Storage → Clear all history. The uninstall guide shows where to remove the sandbox-container data if you want a complete cleanup." },
  ];

  const [showAll, setShowAll] = React.useState(false);

  function onFaqToggle(e) {
    if (e.target.open) window.plausible && window.plausible('FAQ Expand');
  }

  return (
    <section className="faq-section" aria-labelledby="faq-heading">
      <div className="container faq-container">
        <div className="section-eyebrow">Common questions</div>
        <h2 id="faq-heading" className="section-title">Questions, answered.</h2>
        <p className="section-lede">The practical details — privacy, compatibility, updates, storage, and what to expect after installing.</p>
        <div className="faq-list">
          {faqs.map((f, i) => (
            <details key={i} className="faq-item" onToggle={onFaqToggle} hidden={i >= 6 && !showAll}>
              <summary>{f.q}</summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
        <div className="faq-actions">
          {!showAll && <button type="button" className="btn btn-ghost" onClick={() => setShowAll(true)}>Show 8 more answers</button>}
          <a className="section-more" href="/faq/">Open the complete help guide <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </section>
  );
}

function DownloadSection() {
  const downloadUrl = useDownloadUrl();
  return (
    <section className="download" id="download" aria-labelledby="download-heading">
      <div className="container">
        <div className="download-card">
          <h2 id="download-heading">Stop losing what you copy.</h2>
          <p>Free and open source. Clipboard history stays on your Mac with no cloud sync. Two minutes to install.</p>
          <div className="hero-actions">
            <a href={downloadUrl} className="btn btn-primary btn-lg" onClick={() => window.plausible && window.plausible('Download Click', { props: { source: 'closing' } })}>
              <span aria-hidden="true"><Icon.apple/></span> Download free for Mac
            </a>
            <a href="https://github.com/gug007/clipboard-history" className="btn btn-ghost btn-lg">
              <span aria-hidden="true"><Icon.github/></span> View source on GitHub
            </a>
          </div>
          <ul className="download-meta" aria-label="Download details">
            <li className="download-meta-item" data-tone="blue"><span className="dm-icon" aria-hidden="true"><Icon.apple/></span> macOS 14 or later</li>
            <li className="download-meta-item" data-tone="green"><span className="dm-icon" aria-hidden="true"><Icon.download/></span> Local-only history</li>
            <li className="download-meta-item" data-tone="amber"><span className="dm-icon" aria-hidden="true"><Icon.bolt/></span> Apple Silicon and Intel</li>
            <li className="download-meta-item" data-tone="purple"><span className="dm-icon" aria-hidden="true"><Icon.shield/></span> Signed and notarized</li>
          </ul>
        </div>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="foot" aria-label="Site footer">
      <div className="container foot-inner">
        <div>© 2026 Clipboard History · MIT License</div>
        <nav className="foot-links" aria-label="Footer">
          <a href="https://github.com/gug007/clipboard-history">GitHub</a>
          <a href="https://github.com/gug007/clipboard-history/releases">Releases</a>
          <a href="/download/">Download for Mac</a>
          <a href="/mac-clipboard-history/">Mac clipboard guide</a>
          <a href="/keyboard-shortcuts/">Keyboard shortcuts</a>
          <a href="/security/">Security</a>
          <a href="/faq/">Help and FAQ</a>
          <a href="/best-free-clipboard-managers-mac/">Best free Mac apps</a>
          <a href="/privacy/">Privacy</a>
          <a href="/uninstall/">Uninstall</a>
          <a href="https://github.com/gug007/clipboard-history/issues">Support</a>
        </nav>
      </div>
    </footer>
  );
}

window.PrivacySection = PrivacySection;
window.CheatsheetSection = CheatsheetSection;
window.FAQSection = FAQSection;
window.DownloadSection = DownloadSection;
window.Footer = Footer;
